language: node_js

node_js:
  - 6

cache: yarn

deploy:
  provider: npm
  email: npm-bot@mondora.com
  api_key: $NPM_TOKEN
  on:
    tags: true

before_deploy:
  - yarn install
  - yarn compile

script:
  - yarn lint
  - yarn coverage
  - yarn coveralls
