language: node_js

node_js:
  - 6

cache: yarn

deploy:
  provider: npm
  email: npm-bot@mondora.com
  api_key: $NPM_TOKEN
  on:
    tags: true
  skip_cleanup: true

script:
  - yarn lint
  - yarn coverage
  - yarn coveralls
  - yarn compile
